@ECHO OFF
::
:: Set the build paremeters
::

SET OSDKADDR=$2000
SET OSDKNAME=pelancia
SET OSDKLINK=-B
SET OSDKHEAD=-S1 -a0
SET OSDKFILE= elancia

:SET OSDKADDR=$2000
:SET OSDKNAME=pkaeso
:SET OSDKLINK=-B
:SET OSDKHEAD=-S1 -a0
:SET OSDKFILE= kaeso

:SET OSDKADDR=$2000
:SET OSDKNAME=pmaelle
:SET OSDKLINK=-B
:SET OSDKHEAD=-S1 -a0
:SET OSDKFILE= maelle

:SET OSDKADDR=$2000
:SET OSDKNAME=pcarpo
:SET OSDKLINK=-B
:SET OSDKHEAD=-S1 -a0
:SET OSDKFILE= carpo

:SET OSDKADDR=$2000
:SET OSDKNAME=pviggo
:SET OSDKLINK=-B
:SET OSDKHEAD=-S1 -a0
:SET OSDKFILE= viggo

:SET OSDKADDR=$2000
:SET OSDKNAME=pastrid
:SET OSDKLINK=-B
:SET OSDKHEAD=-S1 -a0
:SET OSDKFILE= astrid

:SET OSDKADDR=$2000
:SET OSDKNAME=pcirig
:SET OSDKLINK=-B
:SET OSDKHEAD=-S1 -a0
:SET OSDKFILE= cirig

:SET OSDKADDR=$2000
:SET OSDKNAME=pkennet
:SET OSDKLINK=-B
:SET OSDKHEAD=-S1 -a0
:SET OSDKFILE= kennet

:SET OSDKADDR=$2000
:SET OSDKNAME=pmcnarod
:SET OSDKLINK=-B
:SET OSDKHEAD=-S1 -a0
:SET OSDKFILE= mcnarod




