#labels
#optimize
 END
 GOTO Asm
 GOTO Cprog
 GOTO Bas
 GOTO Tests
 GOTO OldData
 GOTO Tabs
Asm
 DEL "MAP.COM"
 COPY "B-MAP.COM" TO A
 END
 DEL "VILLE1.COM" 
 COPY "B-VILLE1.COM" TO A
 END
 DEL "VILLE2.COM" 
 COPY "B-VILLE2.COM" TO A
 END
Cprog
 DEL "CAMP.COM"
 COPY "B-CAMP.COM" TO A
 END
Bas  
 DEL "COPL.COM"
 COPY "B-COPL.COM" TO "A-COPL.COM"
 END
 DEL "COMBAT.COM"
 COPY "B-COMBATL.COM" TO "A-COMBAT.COM"
 END
 DEL "ARM.COM"
 COPY "B-ARMORYL.COM" TO "A-ARM.COM"
 END
 DEL "MED.COM"
 COPY "B-MEDICL.COM" TO "A-MED.COM"
 END
 DEL "HER.COM"
 COPY "B-HERBOL.COM" TO "A-HER.COM"
 END
 DEL "ANI.COM"
 COPY "B-ANIMALSL.COM" TO "A-ANI.COM"
 END
 DEL "BAZ.COM"
 COPY "B-BAZARL.COM" TO "A-BAZ.COM"
 END
 DEL "TAB.COM"
 COPY "B-TABERNAL.COM" TO "A-TAB.COM"
 END
Tests 
 DEL "T4TEAM.COM"
 COPY "B-T4TEAM.COM" TO A
 END
OldData 
 DEL "TEAM.BIN"
 COPY "C-TEAM.BIN" TO A
 END
Tabs
 COPY "B-TITEMSL.COM" TO A 
 TITEMSL
 DEL "TITEMSL.COM"
 COPY "B-TPRIXL.COM" TO A 
 TPRIXL
 DEL "TPRIXL.COM"
 COPY "B-MONSTRESL.COM" TO A 
 MONSTRESL
 DEL "MONSTRESL.COM"