#labels
#optimize
 REM {+ ORIC 2014-15 + TYRANN 3 + MAXIMUS => TYRANN 4 + Hialmar +}
 TEXT:LOAD "FONT.BIN":PAPER0:INK6
 POKE 48035,0:POKE#26A,PEEK(#26A)AND254
Start 
 CLS
 FR=FRE("")
 PRINT@5, 8;"1- START THE INTRODUCTION"
 PRINT@5,10;"2- CREATE A NEW TEAM"
 PRINT@5,12;"3- CONTINUE PLAYING"
 PRINT@5,14;"4- RESTART WITH CURRENT TEAM"
 PRINT@5,16;"5- QUIT"
 PRINT
 INPUT "YOUR CHOICE";CH 
 IF CH=1 THEN LOAD "INTRO"
 IF CH=2 THEN LOAD "CREATION"
 IF CH=3 THEN LOAD "MAP"
 IF CH=4 THEN GOSUB Restart
 IF CH=5 THEN END
 GOTO Start
Restart
 CLS
 PRINT "WARNING YOU WILL LOOSE ALL EQUIPMENT, GOLD AND XP"
Sure
 PRINT "ARE YOU SURE Y/N"
 GET A$
 IF A$ = "N" THEN RETURN
 IF A$ <> "Y" THEN Sure
 COPYO "TEAM2.BIN" TO "TEAM.BIN"
 LOAD "MAP"